/*COMPLETED BY: Bethany Cooper */
BEGIN;
INSERT INTO questions VALUES (1, 'Thinking up new ideas and being creative is important to you. You like to do things in your own original way.', 'self_direction',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (2, 'It is important to you to be rich. You want to have a lot of money and expensive things.', 'power',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (3, 'You think it is important that every person in the world should be treated equally. You believe everyone should have equal opportunities in life.', 'universalism',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (4, 'It''s important to you to show your abilities. You want people to admire what you do.', 'achievement',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (5, 'It is important to you to live in secure surroundings. You avoid anything that might endanger your safety.', 'security',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (6, 'You like surprises and are always looking for new things to do. You think it is important to do lots of different things in life.', 'stimulation',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (7, 'You believe that people should do what they''re told. You think people should follow rules at all times, even when no-one is watching.', 'conformity',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (8, 'It is important to you to listen to people who are different from you. Even when you disagree with them, you still want to understand them.', 'universalism',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (9, 'It is important to you to be humble and modest. You try not to draw attention to yourself.', 'tradition',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (10, 'Having a good time is important to you. You like to “spoil” yourself.', 'hedonism',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (11, 'It is important to you to make your own decisions about what you do. You like to be free and not depend on others.', 'self_direction',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (12, 'It''s very important to you to help the people around you. You want to care for their well-being.', 'benevolence',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (13, 'Being very successful is important to you. You hope people will recognise your achievements.', 'achievement',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (14, 'It is important to you that the government ensures your safety against all threats. You want the state to be strong so it can defend its citizens.', 'security',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (15, 'You look for adventures and like to take risks. You want to have an exciting life.', 'stimulation',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (16, 'It is important to you always to behave properly. You want to avoid doing anything people would say is wrong.', 'conformity',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (17, 'It is important to you to get respect from others. You want people to do what you say.', 'power',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (18, 'It is important to you to be loyal to your friends. You want to devote yourself to people close to you.', 'benevolence',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (19, 'You strongly believe that people should care for nature. Looking after the environment is important to you.', 'universalism',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (20, 'Tradition is important to you. You try to follow the customs handed down by your religion or your family.', 'tradition',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
INSERT INTO questions VALUES (21, 'You seek every chance you can to have fun. It is important to you to do things that give you pleasure.', 'hedonism',
                              ARRAY[(6, 'Very much like me')::question_option, (5, 'Like me')::question_option, (4, 'Somewhat like me')::question_option, (3, 'A little like me')::question_option, (2, 'Not like me')::question_option, (1, 'Not like me at all')::question_option, (0, 'Don’t know')::question_option]);
COMMIT;
